name: Data Cleaning Workflow

on:
  push:
    paths:
      - 'data/raw_data.csv'  # Trigger when the raw_data.csv file is updated

jobs:
  clean_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install pandas

      - name: Run Data Cleaning Script
        run: |
          python data_cleaning.py
